spring.application.name=perfume-manager-api
# 1. Configuración de la conexión física a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
# REEMPLAZA AQUÍ: Pon la contraseña exacta que creaste cuando instalaste PostgreSQL
spring.datasource.password=2106
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuración de la estrategia de JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
